# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scribe < Formula
  desc "Team skill sync CLI for AI coding agents"
  homepage "https://github.com/Naoray/scribe"
  version "0.1.0-alpha.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Naoray/scribe/releases/download/v0.1.0-alpha.1/scribe_darwin_amd64.tar.gz"
      sha256 "3cb7e20f757b8a1b6e89f6b816e6f76022ec3b6a116372394df4515897f550bd"

      define_method(:install) do
        bin.install "scribe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Naoray/scribe/releases/download/v0.1.0-alpha.1/scribe_darwin_arm64.tar.gz"
      sha256 "255ad4b7601c1b9fbf2655b994bd6492520e45feb661ff8d355516211ccfd73e"

      define_method(:install) do
        bin.install "scribe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Naoray/scribe/releases/download/v0.1.0-alpha.1/scribe_linux_amd64.tar.gz"
      sha256 "a9e580c91e7c12e92c189826747cd6de6f25e63da047da3adf404a0f96bd3a25"
      define_method(:install) do
        bin.install "scribe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Naoray/scribe/releases/download/v0.1.0-alpha.1/scribe_linux_arm64.tar.gz"
      sha256 "8f54dedac0ce7d9070c2c44d98fac69560c0ca5fd91cdeb1c4e7e8e85efb9d61"
      define_method(:install) do
        bin.install "scribe"
      end
    end
  end

  test do
    system "#{bin}/scribe", "--help"
  end
end
