# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scribe < Formula
  desc "Team skill sync CLI for AI coding agents"
  homepage "https://github.com/Naoray/scribe"
  version "0.9.1-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Naoray/scribe/releases/download/v0.9.1-beta.1/scribe_darwin_amd64.tar.gz"
      sha256 "86a5a7138195f030d58588dd4cebadb7ed9614e4b1a3ee58d7c70dd550e77d63"

      define_method(:install) do
        bin.install "scribe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Naoray/scribe/releases/download/v0.9.1-beta.1/scribe_darwin_arm64.tar.gz"
      sha256 "6f5fa97eee57e2d997436d24d2a77bafe8ecb095b38748a5cc91acf596a30320"

      define_method(:install) do
        bin.install "scribe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Naoray/scribe/releases/download/v0.9.1-beta.1/scribe_linux_amd64.tar.gz"
      sha256 "ee71635c9c090c7a0fc3ac891e52a068e54d2ffd7905bd08e3a169f3c636878c"
      define_method(:install) do
        bin.install "scribe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Naoray/scribe/releases/download/v0.9.1-beta.1/scribe_linux_arm64.tar.gz"
      sha256 "4a4e9978cd78f2f9e8c1fb25a302898e0447510371fca485b8b64f468d8332b1"
      define_method(:install) do
        bin.install "scribe"
      end
    end
  end

  test do
    system "#{bin}/scribe", "--version"
  end
end
